# Generated by Django 3.2 on 2021-04-23 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=150)),
                ('created', models.DateField(default=datetime.datetime(2021, 4, 23, 23, 7, 22, 993359, tzinfo=utc))),
                ('favoritos', models.ManyToManyField(to='Favs.Favoritos')),
            ],
        ),
    ]
