# Generated by Django 3.2 on 2021-04-23 23:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Favs', '0002_auto_20210423_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 23, 40, 5, 438193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lista',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='Favs.Favoritos'),
        ),
    ]
