# Generated by Django 3.2 on 2021-04-23 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Favs', '0003_auto_20210423_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 23, 41, 45, 588946, tzinfo=utc)),
        ),
    ]
