# Generated by Django 3.2 on 2021-04-24 00:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Favs', '0006_auto_20210424_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SSO.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 0, 22, 59, 912716, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lista',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 0, 22, 59, 913339, tzinfo=utc)),
        ),
    ]
